/** Icônes proposées à l’étape « avatar » (`/public/avatars/*.png`). */
export const AVATAR_PERSONNAGES: readonly { id: string; nom: string; src: string }[] = [
  { id: 'loup', nom: 'Loup', src: '/avatars/loup.png' },
  { id: 'loup-1', nom: 'Loup 1', src: '/avatars/loup-1.png' },
  { id: 'loup-2', nom: 'Loup 2', src: '/avatars/loup-2.png' },
  { id: 'loup-3', nom: 'Loup 3', src: '/avatars/loup-3.png' },
  { id: 'loup-4', nom: 'Loup 4', src: '/avatars/loup-4.png' },
  { id: 'loup-5', nom: 'Loup 5', src: '/avatars/loup-5.png' },
  { id: 'loup-6', nom: 'Loup 6', src: '/avatars/loup-6.png' },
  { id: 'loup-7', nom: 'Loup 7', src: '/avatars/loup-7.png' },
  { id: 'loup-8', nom: 'Loup 8', src: '/avatars/loup-8.png' },
  { id: 'loup-9', nom: 'Loup 9', src: '/avatars/loup-9.png' },
  { id: 'loup-10', nom: 'Loup 10', src: '/avatars/loup-10.png' },
  { id: 'souris', nom: 'Souris', src: '/avatars/souris.png' },
  { id: 'souris-1', nom: 'Souris 1', src: '/avatars/souris-1.png' },
  { id: 'souris-2', nom: 'Souris 2', src: '/avatars/souris-2.png' },
  { id: 'souris-3', nom: 'Souris 3', src: '/avatars/souris-3.png' },
  { id: 'souris-4', nom: 'Souris 4', src: '/avatars/souris-4.png' },
  { id: 'souris-5', nom: 'Souris 5', src: '/avatars/souris-5.png' },
  { id: 'souris-6', nom: 'Souris 6', src: '/avatars/souris-6.png' },
  { id: 'ours-en-peluche-1', nom: 'Ours 1', src: '/avatars/ours-en-peluche-1.png' },
  { id: 'ours-en-peluche-2', nom: 'Ours 2', src: '/avatars/ours-en-peluche-2.png' },
  { id: 'ours-en-peluche-3', nom: 'Ours 3', src: '/avatars/ours-en-peluche-3.png' },
  { id: 'ours-en-peluche-4', nom: 'Ours 4', src: '/avatars/ours-en-peluche-4.png' },
  { id: 'ours-en-peluche-5', nom: 'Ours 5', src: '/avatars/ours-en-peluche-5.png' },
  { id: 'ours-en-peluche-6', nom: 'Ours 6', src: '/avatars/ours-en-peluche-6.png' },
  { id: 'ours-en-peluche-7', nom: 'Ours 7', src: '/avatars/ours-en-peluche-7.png' },
  { id: 'ours-en-peluche-8', nom: 'Ours 8', src: '/avatars/ours-en-peluche-8.png' },
  { id: 'ours-en-peluche-9', nom: 'Ours 9', src: '/avatars/ours-en-peluche-9.png' },
  { id: 'ours-en-peluche-10', nom: 'Ours 10', src: '/avatars/ours-en-peluche-10.png' },
  { id: 'ours-en-peluche-11', nom: 'Ours 11', src: '/avatars/ours-en-peluche-11.png' },
  { id: 'ours-en-peluche-12', nom: 'Ours 12', src: '/avatars/ours-en-peluche-12.png' },
  { id: 'ours-en-peluche-13', nom: 'Ours 13', src: '/avatars/ours-en-peluche-13.png' },
  { id: 'ours-en-peluche-14', nom: 'Ours 14', src: '/avatars/ours-en-peluche-14.png' },
  { id: 'chat-1', nom: 'Chat 1', src: '/avatars/chat-1.png' },
  { id: 'chat-2', nom: 'Chat 2', src: '/avatars/chat-2.png' },
  { id: 'chat-3', nom: 'Chat 3', src: '/avatars/chat-3.png' },
  { id: 'chat-4', nom: 'Chat 4', src: '/avatars/chat-4.png' },
  { id: 'chaton', nom: 'Chaton', src: '/avatars/chaton.png' },
  { id: 'minou-1', nom: 'Minou 1', src: '/avatars/minou-1.png' },
  { id: 'minou-2', nom: 'Minou 2', src: '/avatars/minou-2.png' },
  { id: 'minou-3', nom: 'Minou 3', src: '/avatars/minou-3.png' },
  { id: 'minou-4', nom: 'Minou 4', src: '/avatars/minou-4.png' },
  { id: 'serpent', nom: 'Serpent', src: '/avatars/serpent.png' },
  { id: 'serpent-1', nom: 'Serpent 1', src: '/avatars/serpent-1.png' },
  { id: 'serpent-2', nom: 'Serpent 2', src: '/avatars/serpent-2.png' },
  { id: 'serpent-3', nom: 'Serpent 3', src: '/avatars/serpent-3.png' },
  { id: 'serpent-4', nom: 'Serpent 4', src: '/avatars/serpent-4.png' },
  { id: 'serpent-5', nom: 'Serpent 5', src: '/avatars/serpent-5.png' },
  { id: 'serpent-6', nom: 'Serpent 6', src: '/avatars/serpent-6.png' },
  { id: 'serpent-7', nom: 'Serpent 7', src: '/avatars/serpent-7.png' },
  { id: 'cameleon', nom: 'Caméléon', src: '/avatars/cameleon.png' },
  { id: 'cameleon-1', nom: 'Caméléon 1', src: '/avatars/cameleon-1.png' },
  { id: 'cameleon-2', nom: 'Caméléon 2', src: '/avatars/cameleon-2.png' },
  { id: 'cameleon-3', nom: 'Caméléon 3', src: '/avatars/cameleon-3.png' },
  { id: 'requin', nom: 'Requin', src: '/avatars/requin.png' },
  { id: 'requin-1', nom: 'Requin 1', src: '/avatars/requin-1.png' },
  { id: 'requin-2', nom: 'Requin 2', src: '/avatars/requin-2.png' },
  { id: 'requin-3', nom: 'Requin 3', src: '/avatars/requin-3.png' },
  { id: 'bailler', nom: 'Bâillement', src: '/avatars/bailler.png' },
  { id: 'biere', nom: 'Bière', src: '/avatars/biere.png' },
  { id: 'cafe', nom: 'Café', src: '/avatars/cafe.png' },
  { id: 'cafe-1', nom: 'Café 1', src: '/avatars/cafe-1.png' },
  { id: 'camera-arriere', nom: 'Photo', src: '/avatars/camera-arriere.png' },
  { id: 'chanter', nom: 'Chant', src: '/avatars/chanter.png' },
  { id: 'chercher', nom: 'Recherche', src: '/avatars/chercher.png' },
  { id: 'content', nom: 'Content', src: '/avatars/content.png' },
  { id: 'courrier', nom: 'Courrier', src: '/avatars/courrier.png' },
  { id: 'danseur', nom: 'Danse', src: '/avatars/danseur.png' },
  { id: 'date-danniversaire', nom: 'Anniversaire', src: '/avatars/date-danniversaire.png' },
  { id: 'detendu', nom: 'Détendu', src: '/avatars/detendu.png' },
  { id: 'dormir-seul', nom: 'Dodo', src: '/avatars/dormir-seul.png' },
  { id: 'entrainement', nom: 'Sport', src: '/avatars/entrainement.png' },
  { id: 'entrainement-1', nom: 'Sport 1', src: '/avatars/entrainement-1.png' },
  { id: 'entreprises', nom: 'Bureau', src: '/avatars/entreprises.png' },
  { id: 'fete', nom: 'Fête', src: '/avatars/fete.png' },
  { id: 'fievre', nom: 'Fièvre', src: '/avatars/fievre.png' },
  { id: 'heure-du-coucher', nom: 'Coucher', src: '/avatars/heure-du-coucher.png' },
  { id: 'hiver', nom: 'Hiver', src: '/avatars/hiver.png' },
  { id: 'idee', nom: 'Idée', src: '/avatars/idee.png' },
  { id: 'il-pleut', nom: 'Pluie', src: '/avatars/il-pleut.png' },
  { id: 'il-pleut-1', nom: 'Pluie 1', src: '/avatars/il-pleut-1.png' },
  { id: 'il-pleut-2', nom: 'Pluie 2', src: '/avatars/il-pleut-2.png' },
  { id: 'malade', nom: 'Malade', src: '/avatars/malade.png' },
  { id: 'manger', nom: 'Repas', src: '/avatars/manger.png' },
  { id: 'marin', nom: 'Marin', src: '/avatars/marin.png' },
  { id: 'motard', nom: 'Motard', src: '/avatars/motard.png' },
  { id: 'ordinateur-portable', nom: 'Ordi', src: '/avatars/ordinateur-portable.png' },
  { id: 'patineur', nom: 'Patinage', src: '/avatars/patineur.png' },
  { id: 'riche', nom: 'Riche', src: '/avatars/riche.png' },
  { id: 'rock-star', nom: 'Rock', src: '/avatars/rock-star.png' },
  { id: 'spa', nom: 'Spa', src: '/avatars/spa.png' },
  { id: 'vacances', nom: 'Vacances', src: '/avatars/vacances.png' },
  { id: 'visage-triste', nom: 'Triste', src: '/avatars/visage-triste.png' },
  { id: 'yoga', nom: 'Yoga', src: '/avatars/yoga.png' },
];

/** Chemins autorisés côté API (validation de l’avatar choisi). */
export const AVATAR_PRESETS: readonly string[] = AVATAR_PERSONNAGES.map((p) => p.src);
